spring:
  application:
    name: SpringbootDockerKubernatesPipelineApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  profiles:
#    active:
#    - test
logging:
  file:
    name: C:/Users/Srinu/Desktop/logs/springbootapplication.log
management:
  tracing:
    sampling:
      probability: 1.0